name: MSVC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  VS2019:
    runs-on: windows-2019

    strategy:
      matrix:
        config: [Debug, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.config}} -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE\vcpkg\scripts\buildsystems\vcpkg.cmake

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --config ${{matrix.config}} -j4

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest --build-config ${{matrix.config}}
